language: java
jdk:
  - openjdk8

branches:
  only:
    - master

before_install:
  - chmod +x gradlew

# Travis CI 서버의 home
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

script: "./gradlew clean build"

before_deploy:
  - zip -r springboot-webservice ./*
  - mkdir -p deploy
  - mv springboot-webservice.zip deploy/springboot-webservice.zip

deploy:
  - provider: s3
  access_key_id: $AWS_ACCESS_KEY #TRAVIS REPO SETTING 설정값
  secret_access_key: $AWS_SECRET_KEY #상동
  bucket: liam-webservice-build #s3버킷
  key: liam-webservice-build.zip
  region: ap-northeast-2
  skip_cleanup: true
  acl: private #zip파일 접근을 private로
  local_dir: deploy
  wait-untill-deploy: true

  - provider: codedeploy
  access_key_id: $AWS_ACCESS_KEY #TRAVIS REPO SETTING 설정값
  secret_access_key: $AWS_SECRET_KEY #상동
  bucket: liam-webservice-build #s3버킷
  key: liam-webservice-build.zip
  bundle-type: zip
  application: springboot-webservice
  deployment_group: springboot-webservice-group
  region: ap-northeast-2
  skip_cleanup: true
  wait-untill-deploy: true
#CI 실행 완료 시 메일로알람
notifications:
  email:
    recipients:
      - godrn1993@naver.com